// Social media platform configurations

export const SOCIAL_PLATFORMS = {
  FACEBOOK: 'facebook',
  TWITTER: 'twitter',
  LINKEDIN: 'linkedin',
  INSTAGRAM: 'instagram',
  YOUTUBE: 'youtube',
  TIKTOK: 'tiktok',
  GITHUB: 'github',
  WEBSITE: 'website',
  EMAIL: 'email',
  PHONE: 'phone',
  WHATSAPP: 'whatsapp',
  TELEGRAM: 'telegram',
  DISCORD: 'discord',
  SPOTIFY: 'spotify',
  BEHANCE: 'behance',
  DRIBBBLE: 'dribbble',
  PINTEREST: 'pinterest',
  SNAPCHAT: 'snapchat',
  TWITCH: 'twitch',
  ZALO: 'zalo',
  MESSENGER: 'messenger'
} as const

export const SOCIAL_PLATFORMS_LIST = [
  { key: 'facebook', name: 'Facebook', icon: '📘', placeholder: 'https://facebook.com/username' },
  { key: 'instagram', name: 'Instagram', icon: '📷', placeholder: 'https://instagram.com/username' },
  { key: 'twitter', name: 'Twitter/X', icon: '🐦', placeholder: 'https://twitter.com/username' },
  { key: 'linkedin', name: 'LinkedIn', icon: '💼', placeholder: 'https://linkedin.com/in/username' },
  { key: 'youtube', name: 'YouTube', icon: '📺', placeholder: 'https://youtube.com/@username' },
  { key: 'tiktok', name: 'TikTok', icon: '🎵', placeholder: 'https://tiktok.com/@username' },
  { key: 'github', name: 'GitHub', icon: '💻', placeholder: 'https://github.com/username' },
  { key: 'website', name: 'Website', icon: '🌐', placeholder: 'https://yourwebsite.com' },
  { key: 'email', name: 'Email', icon: '📧', placeholder: 'your.email@example.com' },
  { key: 'phone', name: 'Phone', icon: '📞', placeholder: '+84 123 456 789' },
  { key: 'whatsapp', name: 'WhatsApp', icon: '💬', placeholder: '+84 123 456 789' },
  { key: 'telegram', name: 'Telegram', icon: '📱', placeholder: '@username' },
  { key: 'discord', name: 'Discord', icon: '🎮', placeholder: 'username#1234' },
  { key: 'spotify', name: 'Spotify', icon: '🎵', placeholder: 'https://open.spotify.com/user/username' },
  { key: 'behance', name: 'Behance', icon: '🎨', placeholder: 'https://behance.net/username' },
  { key: 'dribbble', name: 'Dribbble', icon: '🏀', placeholder: 'https://dribbble.com/username' },
  { key: 'pinterest', name: 'Pinterest', icon: '📌', placeholder: 'https://pinterest.com/username' },
  { key: 'snapchat', name: 'Snapchat', icon: '👻', placeholder: 'username' },
  { key: 'twitch', name: 'Twitch', icon: '🎮', placeholder: 'https://twitch.tv/username' },
  { key: 'zalo', name: 'Zalo', icon: '💙', placeholder: 'https://zalo.me/username' },
  { key: 'messenger', name: 'Messenger', icon: '💬', placeholder: 'https://m.me/username' }
]

export const PLATFORM_ICONS: Record<string, string> = {
  [SOCIAL_PLATFORMS.FACEBOOK]: '📘',
  [SOCIAL_PLATFORMS.INSTAGRAM]: '📷',
  [SOCIAL_PLATFORMS.TWITTER]: '🐦',
  [SOCIAL_PLATFORMS.LINKEDIN]: '💼',
  [SOCIAL_PLATFORMS.YOUTUBE]: '📺',
  [SOCIAL_PLATFORMS.TIKTOK]: '🎵',
  [SOCIAL_PLATFORMS.GITHUB]: '💻',
  [SOCIAL_PLATFORMS.WEBSITE]: '🌐',
  [SOCIAL_PLATFORMS.EMAIL]: '📧',
  [SOCIAL_PLATFORMS.PHONE]: '📞',
  [SOCIAL_PLATFORMS.WHATSAPP]: '💬',
  [SOCIAL_PLATFORMS.TELEGRAM]: '📱',
  [SOCIAL_PLATFORMS.DISCORD]: '🎮',
  [SOCIAL_PLATFORMS.SPOTIFY]: '🎵',
  [SOCIAL_PLATFORMS.BEHANCE]: '🎨',
  [SOCIAL_PLATFORMS.DRIBBBLE]: '🏀',
  [SOCIAL_PLATFORMS.PINTEREST]: '📌',
  [SOCIAL_PLATFORMS.SNAPCHAT]: '👻',
  [SOCIAL_PLATFORMS.TWITCH]: '🎮',
  [SOCIAL_PLATFORMS.ZALO]: '💙',
  [SOCIAL_PLATFORMS.MESSENGER]: '💬',
  default: '🔗'
}

export const PLATFORM_COLORS: Record<string, string> = {
  [SOCIAL_PLATFORMS.FACEBOOK]: 'from-blue-600 to-blue-700',
  [SOCIAL_PLATFORMS.INSTAGRAM]: 'from-pink-500 to-purple-600',
  [SOCIAL_PLATFORMS.TWITTER]: 'from-blue-400 to-blue-500',
  [SOCIAL_PLATFORMS.LINKEDIN]: 'from-blue-700 to-blue-800',
  [SOCIAL_PLATFORMS.YOUTUBE]: 'from-red-500 to-red-600',
  [SOCIAL_PLATFORMS.TIKTOK]: 'from-pink-500 to-purple-500',
  [SOCIAL_PLATFORMS.GITHUB]: 'from-gray-700 to-gray-800',
  [SOCIAL_PLATFORMS.WEBSITE]: 'from-indigo-500 to-purple-600',
  [SOCIAL_PLATFORMS.EMAIL]: 'from-green-500 to-green-600',
  [SOCIAL_PLATFORMS.PHONE]: 'from-green-600 to-green-700',
  [SOCIAL_PLATFORMS.WHATSAPP]: 'from-green-500 to-green-600',
  [SOCIAL_PLATFORMS.TELEGRAM]: 'from-blue-500 to-blue-600',
  [SOCIAL_PLATFORMS.DISCORD]: 'from-indigo-500 to-purple-600',
  [SOCIAL_PLATFORMS.SPOTIFY]: 'from-green-500 to-green-600',
  [SOCIAL_PLATFORMS.BEHANCE]: 'from-blue-600 to-blue-700',
  [SOCIAL_PLATFORMS.DRIBBBLE]: 'from-pink-500 to-red-500',
  [SOCIAL_PLATFORMS.PINTEREST]: 'from-red-500 to-red-600',
  [SOCIAL_PLATFORMS.SNAPCHAT]: 'from-yellow-400 to-yellow-500',
  [SOCIAL_PLATFORMS.TWITCH]: 'from-purple-500 to-purple-600',
  [SOCIAL_PLATFORMS.ZALO]: 'from-blue-500 to-blue-600',
  [SOCIAL_PLATFORMS.MESSENGER]: 'from-blue-500 to-blue-600',
  default: 'from-gray-600 to-gray-700'
} 